### ISSUE TITLE
Selection Cancelled

### ISSUE THREAD

**Issue by smartyw** [an-rahulpandey/cordova-plugin-mediapicker#10]
On iOS:

```
        window.plugins.mediapicker.getAudio(
            function(uri) {
                alert(uri);
            },
            function(err) {
                alert("ERROR:"+err);
            },
            false,
            false);
```

generates error response "Selection cancelled"

**Comment by an-rahulpandey** [comment]
Does it show the audio selection list or it directly show the selection cancelled?

**Comment by smartyw** [comment]
It just returns instantly with "selection cancelled". You do not see the selection list.

**Comment by an-rahulpandey** [comment]
Ok, is there anything in the Xcode log? Also what is the iOS version?

**Comment by f4by0** [comment]
Add key "NSAppleMusicUsageDescription" to plist

**Comment by Babinkrishna** [comment]
generates error response "Selection cancelled"
cordova version 6.0.3
IOS 10.2
