### ISSUE TITLE
Plugin is not working in iOS 10

### ISSUE THREAD

**Issue by bandhavya** [an-rahulpandey/cordova-plugin-mediapicker#11]

**Comment by WinGood** [comment]
Hello, you must add privacy description in your info.plist file, located in your xcode project.

For example:
Privacy - Media Library Usage Description: test2

[screenshot](https://yadi.sk/i/JOEkxnHz3EByZk)

**Comment by an-rahulpandey** [comment]
Will you be able to submit pull request for the same?
