### ISSUE TITLE
iOS. "Add songs to play" subtitle

### ISSUE THREAD

**Issue by WinGood** [an-rahulpandey/cordova-plugin-mediapicker#12]
Hello thanks a lot for your work, your plugin very helped in my project. I have one question, i use plugin as file explorer for selecting one track and then upload it to the server and this line confuses my users.

https://github.com/an-rahulpandey/cordova-plugin-mediapicker/blob/master/src/ios/MediaPicker.m#L19

Will may be better make subtitle as optional or just remove it?

**Comment by an-rahulpandey** [comment]
I have updated that part of code, check Readme.
