### ISSUE TITLE
Delay between selecting a song and the callback, iOS

### ISSUE THREAD

**Issue by ScottMBerger** [an-rahulpandey/cordova-plugin-mediapicker#15]
The delay can last nearly 5 seconds. It would be nice if there was a callback for whether the user selected a song or canceled the picker so that I could present a loader properly.

**Comment by an-rahulpandey** [comment]
Hi,
I don't understand your issue. However plugin send a error callback if the selection is cancelled or if there is any error in conversion.

**Comment by an-rahulpandey** [comment]
More Info needed.
