### ISSUE TITLE
[iOS]GetSong () method takes time .

### ISSUE THREAD

**Issue by Yanchi4425** [an-rahulpandey/cordova-plugin-mediapicker#19]
Hi.
Thank you for a nice plugin.

Running the GetSong () method on iOS takes about 4 seconds.
(Android works in a moment.)
When multiple selection is made, it becomes late by that much.

The behavior of the native itself seems not to be late.
It takes a considerable amount of time from when native processing ends until Success is called.
Is it just a problem with my device?

My environment:
- iPhone6
- iOS 10.3
- Cordova 7.0.1
- Cordova iOS Platform 4.4.0
- cordova-plugin-mediapicker 1.0.2 

Thanks.

**Comment by an-rahulpandey** [comment]
The songs are exported using [AVAssetExportSession](https://developer.apple.com/documentation/avfoundation/avassetexportsession) in iOS.That's why multiple selection takes time because each song is converted one by one.
