### ISSUE TITLE
Where is "audioData" in MediaPicker.h used?

### ISSUE THREAD

**Issue by takahiro-itazuri** [an-rahulpandey/cordova-plugin-mediapicker#20]

**Comment by an-rahulpandey** [comment]
https://github.com/an-rahulpandey/cordova-plugin-mediapicker#methods--usage

**Comment by takahiro-itazuri** [comment]
I read methods & usage in the link.
But I couldn't find any description about audioData.
Why is audioData declared?

**Comment by an-rahulpandey** [comment]
> Why is audioData declared?

Where it is?

**Comment by takahiro-itazuri** [comment]
```
/********* MediaPicker.h Cordova Plugin header *******/

#import <Cordova/CDVPlugin.h>
#import <Cordova/CDV.h>
#import <MediaPlayer/MediaPlayer.h>


@interface MediaPicker : CDVPlugin <MPMediaPickerControllerDelegate> {
    NSString *callbackID;
    NSData *audioData;
    CDVPluginResult *plresult;
    NSMutableArray *songsList;

}

- (void) getAudio:(CDVInvokedUrlCommand*)command;
- (void) deleteSongs:(CDVInvokedUrlCommand *)command;

@end
```

In above script, "audioData" is declared.
But, MediaPicker.m doesn't use "audioData".

**Comment by an-rahulpandey** [comment]
Oh!, you can remove that. I might be doing some experiments and forget to remove it from header file.

**Comment by takahiro-itazuri** [comment]
Oh, I see! I remove "audioData" from hedaer file. Thank you!
