### ISSUE TITLE
Incompatible iOS/Android response

### ISSUE THREAD

**Issue by conor-mac-aoidh** [an-rahulpandey/cordova-plugin-mediapicker#7]
On iOS, I get an Array object in response to the `getAudio` method. Element 0 then points to the response object.

On Android, I just get the response object.

These should be standardised so that the plugin will work with the same frontend on different platforms. I realise that on Android, there is no facility for selecting multiple files. I suggest:
- on iOS, if multiple files requested, return an array
- on iOS if multiple is false, return an object
- on android, just return an object (no change)
- remove the src parameter

**Comment by an-rahulpandey** [comment]
Yes, sure, I already have that in mind. Will try to configure the plugin along with proper error codes, as soon as I get the time.

**Comment by RameshkrishnanV** [comment]
i m not able select .ogg files..will u please clarify this..
