### ISSUE TITLE
Return a message when media picker is cancelled on iOS

### ISSUE THREAD

**Issue by kukukk** [an-rahulpandey/cordova-plugin-mediapicker#8]
Hi,

On Android there is an error message sent back to the JS code when the selection is cancelled. To do the same on iOS add the following code to the mediaPickerDidCancel method. (I have not forked this repo, so I can't send a pull request)

`CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Selection cancelled"];

[self.commandDelegate sendPluginResult:pluginResult callbackId:callbackID];`

**Comment by an-rahulpandey** [comment]
Cheers!
